#!/usr/bin/env python3

import os
import sys

filename = sys.argv[1]

if not os.path.exists(filename):
	with open(filename, "w") as f:
		f.write("el archivo ha sido creado \n")
else:
	print(f"Error, el archivo ya existe: {filename}")
	sys.exit(1)

